# wisecow-nginx-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wisecow-nginx-conf
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 4499 ssl;
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
          proxy_pass http://wisecow-app:4499;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
