apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow-nginx
  process:
    matchDirectories:
      - dir: /bin/
        recursive: true
        action: Block
      - dir: /usr/bin/
        recursive: true
        action: Block
      - dir: /sbin/
        recursive: true
        action: Block
      - dir: /usr/sbin/
        recursive: true
        action: Block
  file:
    matchDirectories:
      - dir: /etc/
        recursive: true
        action: Block
      - dir: /home/
        recursive: true
        action: Block
      - dir: /root/
        recursive: true
        action: Block
