name: CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_APP: ayubazmi/wisecow
  IMAGE_NGINX: ayubazmi/wisecow-nginx
  TAG: latest
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }} # Optional if using kubeconfig

jobs:
  build-and-push:
    runs-on: self-hosted  # Use your runner here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Wisecow app image
        run: docker build -t $IMAGE_APP:$TAG .

      - name: Push Wisecow app image
        run: docker push $IMAGE_APP:$TAG

      - name: Build Wisecow Nginx image
        run: docker build -t $IMAGE_NGINX:$TAG ./nginx

      - name: Push Wisecow Nginx image
        run: docker push $IMAGE_NGINX:$TAG

      - name: Deploy to Kubernetes
        run: |
          cd k8s
          kubectl apply -f .
